import { Router } from 'express';
import whatsAppController from './router.controller';
import { requireAuth, requireRole } from '@/middlewares/auth.middleware';
const router = Router();
router.post('/webhook', whatsAppController.handleWebhook);
router.get('/config', requireAuth, requireRole(["ADMIN"]), whatsAppController.getConfig);
router.put('/config', requireAuth, requireRole(["ADMIN"]), whatsAppController.updateConfig);
router.post('/session/create', requireAuth, requireRole(["ADMIN"]), whatsAppController.createSession);
router.get('/session/qrcode', requireAuth, requireRole(["ADMIN"]), whatsAppController.getQRCode);
router.get('/session/status', requireAuth, requireRole(["ADMIN"]), whatsAppController.getSessionStatus);
router.delete('/session/disconnect', requireAuth, requireRole(["ADMIN"]), whatsAppController.disconnectSession);
router.post('/test', requireAuth, requireRole(["ADMIN"]), whatsAppController.sendTestMessage);
export default router;
