import { Router } from 'express';
import { getSales, saveSale, getSalesAnalytics, processSale, declineSale, getSaleReceipt, updateSale, deleteSale } from './router.controller';
import { requireAuth, requireRole } from '@/middlewares/auth.middleware';
const router = Router();
router.post("/save", requireAuth,requireRole(["ADMIN"]),saveSale);
router.get("/", requireAuth,requireRole(["ADMIN"]), getSales);
router.get("/analytics", requireAuth,requireRole(["ADMIN"]), getSalesAnalytics);
router.patch("/:id/process", requireAuth,requireRole(["ADMIN"]), ...processSale);
router.patch("/:id/decline", requireAuth,requireRole(["ADMIN"]), ...declineSale);
router.get("/:id/receipt", requireAuth,requireRole(["ADMIN"]), ...getSaleReceipt);
router.put("/:id", requireAuth,requireRole(["ADMIN"]), ...updateSale);
router.delete("/:id", requireAuth,requireRole(["ADMIN"]), ...deleteSale);
export default router;
