import type { LucideIcon } from "lucide-react";
import {
  Search,
  ShoppingCart,
  User,
  Heart,
  LayoutGrid,
  Home,
  Box,
  Tag,
  Receipt,
  Banknote,
  Users,
  BarChart3,
  Settings,
  LogOut,
  Plus,
  Minus,
  Check,
  X,
  ChevronRight,
  ChevronDown,
  ChevronUp,
  ArrowRight,
  Filter,
  Star,
  Trash2,
  Pencil,
  Barcode,
  CreditCard,
  Wallet,
  Package,
  Calendar,
  Bell,
  Menu,
  Download,
  Eye,
  Mail,
  Lock,
  Palette,
  Image as ImageIcon,
  MessageCircle,
  Truck,
  Phone,
  MapPin,
  ArrowLeft,
  Upload,
  QrCode,
  Clock,
  RefreshCw,
  AlertCircle,
  CheckCircle2,
  XCircle,
} from "lucide-react";

const MAP = {
  search: Search,
  cart: ShoppingCart,
  user: User,
  heart: Heart,
  grid: LayoutGrid,
  home: Home,
  box: Box,
  tag: Tag,
  receipt: Receipt,
  cash: Banknote,
  users: Users,
  chart: BarChart3,
  settings: Settings,
  logout: LogOut,
  plus: Plus,
  minus: Minus,
  check: Check,
  close: X,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  arrow: ArrowRight,
  filter: Filter,
  star: Star,
  trash: Trash2,
  edit: Pencil,
  barcode: Barcode,
  card: CreditCard,
  wallet: Wallet,
  package: Package,
  calendar: Calendar,
  bell: Bell,
  menu: Menu,
  download: Download,
  eye: Eye,
  mail: Mail,
  lock: Lock,
  palette: Palette,
  image: ImageIcon,
  whatsapp: MessageCircle,
  truck: Truck,
  phone: Phone,
  pin: MapPin,
  back: ArrowLeft,
  upload: Upload,
  qr: QrCode,
  clock: Clock,
  refresh: RefreshCw,
  alert: AlertCircle,
  success: CheckCircle2,
  error: XCircle,
} as const satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof MAP;

export interface IconProps {
  name: IconName;
  size?: number;
  className?: string;
  strokeWidth?: number;
}

export function Icon({ name, size = 18, className, strokeWidth = 1.7 }: IconProps) {
  const Cmp = MAP[name];
  return <Cmp size={size} strokeWidth={strokeWidth} className={className} aria-hidden />;
}
